version: '2'
services:
  # DB
  postgres-dac-projeto:
    container_name: projeto-db
    image: ijm/projeto-db
    build: ./core/postgres
    ports:
     - "5434:5432"
    expose:
     - 5434
    volumes:
      - ./bd:/var/lib/postgresql
       
  #core
  dac-projeto-core:
    container_name: projeto-core
    build: ./core
    image: ijm/projeto-core
    ports:
     - "8082:8080"
     - "4951:4848"
     - "3701:3700"
    links:
     - "postgres-dac-projeto:banco-dac"
  
  #web
  dac-projeto-web:
    container_name: projeto-web
    build: ./web
    image: ijm/dac-projeto-web
    ports:
     - "8083:8080"
     - "4952:4848"
    links:
     - "dac-projeto-core:projeto-core-server"

    
