version: '2'
services:
  dbpostgres:
    container_name: bancopg
    image: postgres
    volumes:
      - ./bd:/var/lib/postgresql
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: projeto
  core:
    container_name: coreapp
    build: ./dac-projeto-core
    image: jose/core
    ports: 
          - "8081:8080"
          - "1098:1099"
          - "1097:1098"
          - "3874:3873"
          - "3701:3700" 
          - "8182:8181"
          - "8010:8009"
    links: 
     - "dbpostgres:host-banco"
  web:
    container_name: webcliente
    build: ./dac-projeto-web
    image: jose/web
    ports: 
     - "8080:8080"
    links: 
     - "core:host-core"
